// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window["go"]["main"]["App"]["ChooseFolder"]();
}

export function Invite(arg1) {
  return window["go"]["main"]["App"]["Invite"](arg1);
}

export function Maximize() {
  return window["go"]["main"]["App"]["Maximize"]();
}

export function Minimize() {
  return window["go"]["main"]["App"]["Minimize"]();
}

export function Quit() {
  return window["go"]["main"]["App"]["Quit"]();
}

export function Version() {
  return window["go"]["main"]["App"]["Version"]();
}

export function Zrok(arg1) {
  return window["go"]["main"]["App"]["Zrok"](arg1);
}
