// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder():Promise<string>;

export function Invite(arg1:string):Promise<string>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function Overview():Promise<string>;

export function Quit():Promise<void>;

export function Version():Promise<string>;

export function Zrok(arg1:Array<string>):Promise<string>;
