// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Invite(arg1:string):Promise<string>;

export function Zrok(arg1:Array<string>):Promise<string>;
