// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function DeleteShare(arg1) {
  return window['go']['main']['App']['DeleteShare'](arg1);
}

export function Disable() {
  return window['go']['main']['App']['Disable']();
}

export function Enable(arg1) {
  return window['go']['main']['App']['Enable'](arg1);
}

export function Invite(arg1) {
  return window['go']['main']['App']['Invite'](arg1);
}

export function IsEnable() {
  return window['go']['main']['App']['IsEnable']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Request(arg1) {
  return window['go']['main']['App']['Request'](arg1);
}

export function Sharing(arg1) {
  return window['go']['main']['App']['Sharing'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
