// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Invite(arg1) {
  return window['go']['main']['App']['Invite'](arg1);
}

export function Zrok(arg1) {
  return window['go']['main']['App']['Zrok'](arg1);
}
