// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sdk} from '../models';

export function ChooseFolder():Promise<string>;

export function DeleteShare(arg1:sdk.Share):Promise<boolean>;

export function Disable():Promise<boolean>;

export function Enable(arg1:string):Promise<boolean>;

export function Invite(arg1:string):Promise<string>;

export function IsEnable():Promise<boolean>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function Overview():Promise<string>;

export function Quit():Promise<void>;

export function Sharing(arg1:sdk.ShareRequest):Promise<sdk.Share>;

export function Version():Promise<string>;
